# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: introduce
    weight: 10

  - parent: 소개
    name: 연혁
    url: life
    weight: 11
  - parent: 소개
    name: 군대
    url: military
    weight: 12
  - parent: 소개
    name: 테스트
    url: 테스트
    weight: 13


  - name: 활동
    url: post
    weight: 20

  - parent: 활동
    name: 연구실
    url: lab
    weight: 21
  - parent: 활동
    name: 동아리
    url: club
    weight: 22

  - name: 관심사
    url: attract
    weight: 30
  
  - parent: 관심사
    name: 주식
    url: stocks
    weight: 31
  - parent: 관심사
    name: 정치/시사
    url: politics
    weight: 32

  - name: 프로젝트
    url: publication
    weight: 40

  - name: 취미
    url: hobbies
    weight: 60

  - parent: 취미
    name: 공연 관람
    url: concert
    weight: 61
  - parent: 취미
    name: 축구 관람
    url: soccer
    weight: 62

  - name: 연락처
    url: contact
    weight: 70
